###  Hello endpoint
GET http://localhost:8080/api/hello HTTP/1.1


### List Products
# @name ProductList
GET http://localhost:8080/api/products HTTP/1.1

### LSave Products
# @name SaveProduct
POST http://localhost:8080/api/products HTTP/1.1
Content-Type:  application/json

{
    "name": "ASUS",
    "warrant": "2 years", 
    "price": 300000
}

##warrant is ignored-not expected by the controller