server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/product_service
        username: isabel
        password: Seniordev15*
    application:
        name: product-service
    jpa:
        show-sql: true
        hibernate:
         ddl-auto: update